"""empty message

Revision ID: 85b1c4a56803
Revises: b39e7cc61304
Create Date: 2022-02-07 12:40:33.117609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85b1c4a56803'
down_revision = 'b39e7cc61304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('sort_weight', sa.Integer(), nullable=False, default=0))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
